name: Application Build Job

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Decrypt Application properties
      run: |
           echo "${{ secrets.SUPER_SECRET }}" >> ansiblekey
           ansible-vault decrypt src/main/resources/application.properties --vault-pass-file ansiblekey
           ansible-vault decrypt src/main/resources/application-prod.properties --vault-pass-file ansiblekey
                      

    - name: Build with Maven
      run: mvn clean install

    - name: Sonar Scan 
      run: |
         mvn clean verify sonar:sonar \
          -Dsonar.projectKey=appsecurity \
          -Dsonar.projectName='appsecurity' \
          -Dsonar.host.url=http://hivemet.com:9000 \
          -Dsonar.token=${{ secrets.APPSECURITY_KEY }}

    - name: Build Docker Image
      run: |
            docker build -t mkumarda/appsecurity:1.0.0 .
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker push mkumarda/appsecurity:1.0.0

    

   
